services:
  # 1. The Database
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The API Gateway
  api:
    build: ../neurolearn-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../neurolearn-api:/app
  
  # 2. The AI Service
  brain:
    build: ../neurolearn-brain
    expose:
      - "8001"
    volumes:
      - ../neurolearn-brain:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}


  # 3. The Frontend
  web:
    build: ../neurolearn-web
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    volumes:
      - ../neurolearn-web:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: